_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  automated_cron: 0
  better_local_tasks: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  drupal_ftp_global_vars: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  encrypt: 0
  entity_type_clone: 0
  feeds: 0
  feeds_ex: 0
  feeds_tamper: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  ga_login: 0
  google_tag: 0
  help: 0
  history: 0
  image: 0
  key: 0
  language: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  prevnext: 0
  profile_switcher: 0
  rdf: 0
  real_aes: 0
  redirect: 0
  search: 0
  shortcut: 0
  simple_sitemap: 0
  smart_trim: 0
  superfish: 0
  system: 0
  tamper: 0
  taxonomy: 0
  text: 0
  tfa: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  upgrade_status: 0
  user: 0
  views_infinite_scroll: 0
  views_ui: 0
  youtube: 0
  pathauto: 1
  trailing_slash: 1
  views: 10
  mm_drupal_core_d9_shared_infra: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap4: 0
  nl: 0
profile: mm_drupal_core_d9_shared_infra
