entity_type_groups:
  node:
    article:
      basic: basic
      advanced: advanced
      open_graph: open_graph
    attorney:
      basic: basic
      advanced: advanced
      open_graph: open_graph
    page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
    practice_area:
      basic: basic
      advanced: advanced
      open_graph: open_graph
tag_trim_end: '|.,-:;/+&([{"'''
