_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 79cdd82a-9cce-40f3-b27c-e51e6dcf75f7
name: 'Nation Law'
mail: joshua.scott.feinstein@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/5
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
