#!/bin/bash

set -eo pipefail

# Do not run certain build jobs on the template repo.
if [[ "$CI_PROJECT_REPONAME" == 'mm-drupal-site-template-d9' ]]
then
  echo "Template repository does not deploy to Pantheon, nothing to do."
else

  #
  # This script makes the preparations
  # needed to run Behat tests.
  #

  # Authenticate with Terminus
  terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

  # Run composer install again to get dev dependencies
  composer install --no-ansi --no-interaction --optimize-autoloader --no-progress

  # Figure out if we're on master or not.
  if [[ $CI_BRANCH != $DEFAULT_BRANCH ]]
  then
    MDE_ENVIRONMENT=${CI_BRANCH}
  else
    # Push to the dev environment
    MDE_ENVIRONMENT='dev'
  fi

  # Wake the multidev environment before running tests
  terminus -n env:wake $TERMINUS_SITE.$MDE_ENVIRONMENT

  # Ping Drush to start ssh with the app server
  terminus -n drush $TERMINUS_SITE.$MDE_ENVIRONMENT -- version

fi
